Try to fix workflow

diff --git a/.github/actions/Build_and_Test_CppInterOp/action.yml b/.github/actions/Build_and_Test_CppInterOp/action.yml
--- a/.github/actions/Build_and_Test_CppInterOp/action.yml
+++ b/.github/actions/Build_and_Test_CppInterOp/action.yml
@@ -6,8 +6,17 @@ runs:
   steps:
     - name: Build and Test/Install CppInterOp
       if: ${{ runner.os != 'Windows' && !endsWith(matrix.name, '-emscripten') }}
-      shell: bash
+      shell: bash -l {0}
       run: |
+        set -e
+        ./emsdk/emsdk activate ${{matrix.emsdk_ver}}
+        source ./emsdk/emsdk_env.sh
+        micromamba create -f environment-wasm.yml --platform=emscripten-wasm32 -c https://prefix.dev/emscripten-forge-4x -c https://prefix.dev/conda-forge
+        export SYSROOT_PATH=$PWD/emsdk/upstream/emscripten/cache/sysroot
+        export PREFIX=$MAMBA_ROOT_PREFIX/envs/CppInterOp-wasm
+        export CMAKE_PREFIX_PATH=$PREFIX
+        export CMAKE_SYSTEM_PREFIX_PATH=$PREFIX
+
         LLVM_DIR="$(pwd)/llvm-project"
         LLVM_BUILD_DIR="$(pwd)/llvm-project/build"
         cling_on=$(echo "${{ matrix.cling }}" | tr '[:lower:]' '[:upper:]')
@@ -19,65 +28,154 @@ runs:
           CPLUS_INCLUDE_PATH="${LLVM_DIR}/llvm/include:${LLVM_DIR}/clang/include:${LLVM_BUILD_DIR}/include:${LLVM_BUILD_DIR}/tools/clang/include:$PWD/include"
         fi
 
-        export CB_PYTHON_DIR="$PWD/cppyy-backend/python"
-        export CPPINTEROP_DIR="$CB_PYTHON_DIR/cppyy_backend"
-
         # Build CppInterOp next to cling and llvm-project.
-        mkdir build && cd build
-        export CPPINTEROP_BUILD_DIR=$PWD
-        cling_on=$(echo "${{ matrix.cling }}" | tr '[:lower:]' '[:upper:]')
+        mkdir build
+        cd build
         if [[ "${cling_on}" == "ON" ]]; then
-          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}        \
+          emcmake cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}        \
                 -DCPPINTEROP_USE_CLING=ON                                  \
                 -DCPPINTEROP_USE_REPL=OFF                                  \
-                -DCPPINTEROP_INCLUDE_DOCS=${{ matrix.documentation }} \
+                -DCMAKE_PREFIX_PATH=$PREFIX                     \
                 -DCling_DIR=$LLVM_BUILD_DIR/tools/cling         \
                 -DLLVM_DIR=$LLVM_BUILD_DIR/lib/cmake/llvm       \
+                -DLLD_DIR=$LLVM_BUILD_DIR/lib/cmake/lld         \
                 -DClang_DIR=$LLVM_BUILD_DIR/lib/cmake/clang     \
                 -DBUILD_SHARED_LIBS=ON                          \
                 -DCODE_COVERAGE=${{ env.CODE_COVERAGE }}        \
-                -DCMAKE_INSTALL_PREFIX=$CPPINTEROP_DIR          \
-                -DLLVM_ENABLE_WERROR=On                         \
+                -DCMAKE_INSTALL_PREFIX=$PREFIX         \
+                -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON            \
+                -DLLVM_ENABLE_WERROR=On                      \
+                -DSYSROOT_PATH=$SYSROOT_PATH               \
                 ../
         else
-          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}     \
-                -DCPPINTEROP_INCLUDE_DOCS=${{ matrix.documentation }} \
-                -DLLVM_DIR=$LLVM_BUILD_DIR/lib/cmake/llvm    \
-                -DClang_DIR=$LLVM_BUILD_DIR/lib/cmake/clang  \
-                -DBUILD_SHARED_LIBS=ON                       \
-                -DCODE_COVERAGE=${{ env.CODE_COVERAGE }}     \
-                -DCMAKE_INSTALL_PREFIX=$CPPINTEROP_DIR       \
+          emcmake cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}    \
+                -DCMAKE_PREFIX_PATH=$PREFIX                      \
+                -DLLVM_DIR=$LLVM_BUILD_DIR/lib/cmake/llvm       \
+                -DLLD_DIR=$LLVM_BUILD_DIR/lib/cmake/lld         \
+                -DClang_DIR=$LLVM_BUILD_DIR/lib/cmake/clang     \
+                -DBUILD_SHARED_LIBS=ON                      \
+                -DCODE_COVERAGE=${{ env.CODE_COVERAGE }}    \
+                -DCMAKE_INSTALL_PREFIX=$PREFIX      \
+                -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON            \
                 -DLLVM_ENABLE_WERROR=On                      \
-                -DLLVM_BUILT_WITH_OOP_JIT=${{ matrix.oop-jit }} \
+                -DSYSROOT_PATH=$SYSROOT_PATH                     \
                 ../
         fi
-        docs_on=$(echo "${{ matrix.documentation }}" | tr '[:lower:]' '[:upper:]')
-        if [[ "${docs_on}" == "ON" ]]; then
-          cmake --build . --target doxygen-cppinterop --parallel ${{ env.ncpus }}
-          cmake --build . --target sphinx-cppinterop --parallel ${{ env.ncpus }}
+        emmake make -j ${{ env.ncpus }} check-cppinterop
+        os="${{ matrix.os }}"
+        if [[ "${os}" != macos* ]] ; then
+          actual_size=$(stat -c%s "./lib/libclangCppInterOp.so")
+          max_size=$((50 * 1024 * 1024))
+         if [[ "$actual_size" -gt "$max_size" ]]; then
+            echo "Error: libclangCppInterOp.so is larger than 50 MB."
+            exit 1
+         fi
+        fi
+        cd ./unittests/CppInterOp/
+        # Fresh install browsers, and run Emscripten tests in them
+        # This is to match the Emscripten build instructions, where
+        # we run in a fresh browser, to stop any extra installed
+        # stuff interferring with the running of the tests
+        # Explaination of options for emrun
+        # --browser (name of browser on path)
+        # --kill_exit makes it so that when emrun finishes,
+        # that the headless browser we create is killed along with it
+        # --timeout 60 is such that emrun is killed after 60 seconds if
+        # still running. emrun should have finished long before then,
+        # so if it is still running, something went wrong (such as a test
+        # which crashed the html file). This will cause the ci to fail,
+        # as a non 0 value of will be returned.
+        # In the case of Chrome we have the extra --no-sandbox flag, as on
+        # Ubuntu Chrome will refuse to run otherwise, as it expects to have
+        # been installed with admin privileges. This flag allows it to run
+        # in userspace.
+        os="${{ matrix.os }}"
+        if [[ "${os}" == "macos"* ]]; then
+          # Install Firefox
+          wget "https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US" -O Firefox-latest.dmg
+          hdiutil attach Firefox-latest.dmg
+          cp -r /Volumes/Firefox/Firefox.app $PWD
+          hdiutil detach /Volumes/Firefox
+          cd ./Firefox.app/Contents/MacOS/
+          export PATH="$PWD:$PATH"
+          cd -
+
+          # Install Google Chrome
+          wget https://dl.google.com/chrome/mac/stable/accept_tos%3Dhttps%253A%252F%252Fwww.google.com%252Fintl%252Fen_ph%252Fchrome%252Fterms%252F%26_and_accept_tos%3Dhttps%253A%252F%252Fpolicies.google.com%252Fterms/googlechrome.pkg
+          pkgutil --expand-full googlechrome.pkg google-chrome
+          cd ./google-chrome/GoogleChrome.pkg/Payload/Google\ Chrome.app/Contents/MacOS/
+          export PATH="$PWD:$PATH"
+          cd -
+
+          # Run tests in browsers
+          echo "Running CppInterOpTests in Firefox"
+          emrun --browser="firefox" --kill_exit --timeout 60 --browser-args="--headless"  CppInterOpTests.html
+          echo "Running DynamicLibraryManagerTests in Firefox"
+          emrun --browser="firefox" --kill_exit --timeout 60 --browser-args="--headless"  DynamicLibraryManagerTests.html
+          echo "Running CppInterOpTests in Google Chrome"
+          emrun --browser="Google Chrome" --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  CppInterOpTests.html
+          echo "Running DynamicLibraryManagerTests in Google Chrome"          
+          emrun --browser="Google Chrome" --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  DynamicLibraryManagerTests.html
+          sudo safaridriver --enable
+          python -m pip install selenium
+          echo "Running CppInterOpTests in Safari"
+          emrun --no_browser --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  CppInterOpTests.html &
+          python ../../../scripts/browser_tests_safari.py CppInterOpTests.html
+          echo "Running DynamicLibraryManagerTests in Safari"          
+          emrun --no_browser --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  DynamicLibraryManagerTests.html &
+          python ../../../scripts/browser_tests_safari.py DynamicLibraryManagerTests.html
         else
-          cmake --build . --target check-cppinterop --parallel ${{ env.ncpus }}
-          os="${{ matrix.os }}"
-          if [[ "${os}" != "macos"* && "${{ matrix.Valgrind }}" == "On" ]]; then
-            CLANG_VERSION="${{ matrix.clang-runtime }}"
-            if [[ "$CLANG_VERSION" == "20" && "${{ matrix.cling }}" == "Off" ]]; then
-              SUPPRESSION_FILE="../etc/clang${CLANG_VERSION}-valgrind.supp"
-              valgrind --show-error-list=yes --track-origins=yes --error-exitcode=1 \
-                --show-leak-kinds=definite,possible \
-                --suppressions="${SUPPRESSION_FILE}" \
-                unittests/CppInterOp/bin/${{ env.BUILD_TYPE }}/CppInterOpTests
-            else
-              valgrind --show-error-list=yes --track-origins=yes --error-exitcode=1 \
-                --show-leak-kinds=definite,possible \
-                unittests/CppInterOp/bin/${{ env.BUILD_TYPE }}/CppInterOpTests
-            fi
+          export ARCHITECHURE=$(uname -m)
+          if [[ "$ARCHITECHURE" != "aarch64" ]]; then
+            # Install Google Chrome
+            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+            dpkg-deb -x google-chrome-stable_current_amd64.deb $PWD/chrome
+            cd ./chrome/opt/google/chrome/
+            export PATH="$PWD:$PATH"
+            cd -
+
+            # Install Firefox
+            wget https://ftp.mozilla.org/pub/firefox/releases/138.0.1/linux-x86_64/en-GB/firefox-138.0.1.tar.xz
+            tar -xJf firefox-138.0.1.tar.xz
+            cd ./firefox
+            export PATH="$PWD:$PATH"
+            cd -
+
+            # Run tests in browsers
+            echo "Running CppInterOpTests in Firefox"
+            emrun --browser="firefox" --kill_exit --timeout 60 --browser-args="--headless"  CppInterOpTests.html
+            echo "Running DynamicLibraryManagerTests in Firefox"
+            emrun --browser="firefox" --kill_exit --timeout 60 --browser-args="--headless"  DynamicLibraryManagerTests.html
+            echo "Running CppInterOpTests in Google Chrome"
+            emrun --browser="google-chrome" --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  CppInterOpTests.html
+            echo "Running DynamicLibraryManagerTests in Google Chrome"          
+            emrun --browser="google-chrome" --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  DynamicLibraryManagerTests.html
+          else
+            # Install Firefox
+            wget https://ftp.mozilla.org/pub/firefox/releases/138.0.1/linux-aarch64/en-GB/firefox-138.0.1.tar.xz
+            tar -xJf firefox-138.0.1.tar.xz
+            cd ./firefox
+            export PATH="$PWD:$PATH"
+            cd -
+
+            # Run tests in browsers
+            echo "Running CppInterOpTests in Firefox"
+            emrun --browser="firefox" --kill_exit --timeout 60 --browser-args="--headless"  CppInterOpTests.html
+            echo "Running DynamicLibraryManagerTests in Firefox"
+            emrun --browser="firefox" --kill_exit --timeout 60 --browser-args="--headless"  DynamicLibraryManagerTests.html
           fi
         fi
+        cd ../..
+        emmake make -j ${{ env.ncpus }} install
+        cd ..
+
+        echo "PATH=$PATH" >> $GITHUB_ENV
+        echo "SYSROOT_PATH=$SYSROOT_PATH" >> $GITHUB_ENV
         echo "CB_PYTHON_DIR=$CB_PYTHON_DIR" >> $GITHUB_ENV
-        echo "CPPINTEROP_BUILD_DIR=$CPPINTEROP_BUILD_DIR" >> $GITHUB_ENV
         echo "CPPINTEROP_DIR=$CPPINTEROP_DIR" >> $GITHUB_ENV
         echo "LLVM_BUILD_DIR=$LLVM_BUILD_DIR" >> $GITHUB_ENV
         echo "CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH" >> $GITHUB_ENV
+        echo "PREFIX=$PREFIX" >> $GITHUB_ENV  
 
     - name: Build and Test/Install CppInterOp on Windows systems
       if: ${{ runner.os == 'Windows' && !endsWith(matrix.name, '-emscripten') }}
@@ -440,7 +538,7 @@ runs:
         echo "CPPINTEROP_DIR=$CPPINTEROP_DIR" >> $GITHUB_ENV
         echo "LLVM_BUILD_DIR=$LLVM_BUILD_DIR" >> $GITHUB_ENV
         echo "CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH" >> $GITHUB_ENV
-        echo "PREFIX=$PREFIX" >> $GITHUB_ENV
+        echo "PREFIX=$PREFIX" >> $GITHUB_ENV  
 
     - name: Build and Test/Install CppInterOp on Windows systems (shared library)
       if: ${{ runner.os == 'Windows' && endsWith(matrix.name, '-emscripten') }}
@@ -570,7 +668,7 @@ runs:
       if: ${{ runner.os == 'Windows' && endsWith(matrix.name, '-emscripten') && matrix.build_static_library == 'On' && matrix.build_static_library == 'On' }}
       shell: powershell
       run: |
-        .\emsdk\emsdk activate ${{matrix.emsdk_ver}}
+       .\emsdk\emsdk activate ${{matrix.emsdk_ver}}
         .\emsdk\emsdk_env.ps1
         function Error-OnFailure {
           param (
@@ -665,4 +763,4 @@ runs:
         echo "Running CppInterOpTests in Chromium"
         Error-OnFailure { emrun.bat --browser="chrome.exe" --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  CppInterOpTests.html }
         echo "Running DynamicLibraryManagerTests in Chromium"
-        Error-OnFailure{ emrun.bat --browser="chrome.exe" --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  DynamicLibraryManagerTests.html }
+        Error-OnFailure{ emrun.bat --browser="chrome.exe" --kill_exit --timeout 60 --browser-args="--headless --no-sandbox"  DynamicLibraryManagerTests.html }  
